### ISSUE TITLE
修改收款账户的控制账户和收益账户默认数据不对

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#111]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/10653144/163090314-3ffa80b5-5b49-4034-af4a-fe0bd4abf917.png">

切换到验证人账户更改 收款账户 时，控制账户会是上一次切换的账户地址而不是原先链上的控制账户或者当前账户地址，收益账户也会是默认的 Staking 而不是实际现在的收益账户配置

**Comment by JayJay1024** [comment]
「控制账户」似乎是对的？

**Comment by mittwillson** [comment]
@JayJay1024 切换账户后控制账户的值不会变
