### ISSUE TITLE
通过网址在 apps 中区分 crab 和 darwinia

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/apps#118]
比如
https://apps.darwinia.network/#/account/darwinia 进入到 Darwinia 网络中
https://apps.darwinia.network/#/account/crab 进入到 Crab 网络中

**Comment by ZolaxZola** [comment]
URL没有按网络区分开

**Comment by JayJay1024** [comment]
> URL没有按网络区分开

这种格式：
<img width="731" alt="image" src="https://user-images.githubusercontent.com/21007682/165476057-cedd840d-b6d6-4f5d-9575-75e574d68e58.png">

**Comment by ZolaxZola** [comment]
solved
