### ISSUE TITLE
Metamask error

### ISSUE THREAD

**Issue by SasoLithops** [darwinia-network/apps#126]
Hello!

I have tried everything with two of our users reinstalling Crab,refreshing browser,restarting computer increasing gas,MM works well on other chains...still nothing works and this error persists.I also found this article if it helps.

https://community.metamask.io/t/ethjs-query-while-formatting-outputs-from-rpc-value-code-32603-data-code-32000-message-replacement-transaction-underpriced/17751

Many getting this error.But strangelly worked fine by me🤔(last photo)

![IMG_20220425_150708_108.jpg](https://user-images.githubusercontent.com/101176902/165095221-d0310d81-7aa2-4d60-9055-c48ad866ac71.jpg)![IMG_20220425_150714_734.jpg](https://user-images.githubusercontent.com/101176902/165095239-f79ad9d6-88ae-4e15-84fa-2fb0d43e8474.jpg)

![IMG_20220425_141200.jpg](https://user-images.githubusercontent.com/101176902/165095803-45250a33-603f-4047-a756-74ada8ef90b9.jpg)

**Comment by fewensa** [comment]
Thanks for your report.  please try it again

**Comment by boundless-forest** [comment]
Please change your Metamask RPC endpoint to https://darwinia-crab.api.onfinality.io/public/ temporarily.

**Comment by fewensa** [comment]
crab-rpc.darwinia.network also works now

**Comment by SasoLithops** [comment]
Will let them know.Thank you.

Sadly issue persists:

![IMG_20220425_161800_546.jpg](https://user-images.githubusercontent.com/101176902/165108249-0c872003-ec7f-4414-8811-fa88d12ebd72.jpg)

**Comment by SasoLithops** [comment]
Now I will let them know😊

**Comment by SasoLithops** [comment]
They still have errors.

Also when changing this chain id doesn't work.

![IMG_20220425_163050_137.jpg](https://user-images.githubusercontent.com/101176902/165110587-f58cada3-8246-46e4-b105-f004f583fb9d.jpg)

**Comment by SasoLithops** [comment]
Works perfectly for me.

**Comment by boundless-forest** [comment]
![image](https://user-images.githubusercontent.com/11801722/165110810-6a7b8cae-ea35-4853-af6c-39e2538608d3.png)

It works for me. Sometimes you need to wait for  a while(give metamask time to fetch chain id)

**Comment by boundless-forest** [comment]
> Works perfectly for me.

Thanks for your feedback. Congrats. If this problem has been solved, please close this issue.

**Comment by SasoLithops** [comment]
Works perfectly.Thank you so much.We have the best devs💪💪😎

Will close it.Bye.

**Comment by SasoLithops** [comment]
Sorry I am still waiting for anyone that had issue to reply.We are still
getting reports but could be before your fix🤔 As soon as I know will let
you know.

V pon., 25. apr. 2022 15:23 je oseba fewensa ***@***.***>
napisala:

**Comment by boundless-forest** [comment]
@SasoLithops Please resubmit an issue as this has been out of date for a long time. Provide more information about the network and how to reproduce it.

**Comment by SasoLithops** [comment]
Oh sorry.Issue has been solved I guess. I tell them to use dwellir RPC and this error does not happen...
