### ISSUE TITLE
建议隐藏或暂时禁用Darwinia网络下的DVM转换功能

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/apps#140]
Darwinia目前还没有DVM模块，转换后的2开头地址实际并不奏效。如有用户往该工具生成的DVM地址转账，暂时将造成经济损失。
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/102211220/165894502-ae9ed8d7-6fc8-40f7-b68c-7f06967b271d.png">
建议禁用，并给出浮窗提示“Coming Soon” “即将上线”

**Comment by JayJay1024** [comment]
这个应该是提供一个转换的功能。如果是这个情况，可以给一个醒目的提示，而不一定需要禁用？

**Comment by ZolaxZola** [comment]
也行，暂时禁用 是想直接最大限度 避免用户往Darwinia DVM地址里转账
