### ISSUE TITLE
Remove important config

### ISSUE THREAD

**Issue by sxlwar** [darwinia-network/apps#143]
https://github.com/darwinia-network/apps/blob/73d343cd657ccbf6ad0674a4f1454f5598a0c37e/tailwind.config.js#L2

导致内联属性失效等

**Comment by JayJay1024** [comment]
为什么tailwind的这种important写法好像不生效的：
<img width="790" alt="image" src="https://user-images.githubusercontent.com/21007682/167283118-197c0b6e-53f8-4020-b8e3-978064082a63.png">

**Comment by sxlwar** [comment]
是不是需要相关插件支持？没有用过，不是伪类的话可以直接内联样式
