### ISSUE TITLE
Optimization: Show the available RING/KTON amount when users switch their account

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/apps#155]
Show the available RING/KTON amount when users switch their accounts, and at present, click the close button in the upper right corner to exit this page. Is it possible to click the gray part outside the board to exit this page?
![image](https://user-images.githubusercontent.com/80877629/168038186-d56a3213-ddd3-46cd-9f2c-87e1ac34b2eb.png)

**Comment by JayJay1024** [comment]
yep it can close the popup  by clicking the mask(gray part outside).

maybe want to show more info than just available token balance, so I think it's better to show like this #95

**Comment by 1022ranji** [comment]
If shows like #95, it's a little a bit redundant, because users can enter Apps and get the details all. This switch account page is just like a brief prompt, showing transferrable RING and KTON for users to switch accounts(When a user has many accounts, the naming usually exists in an arbitrary state, such as rewards1, rewards2, rewards 3…In this case, the name alone is indistinguishable, and a simple hint such as the available balance can be better distinguished.)
