### ISSUE TITLE
验证人收益参数不能设置 0%

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#157]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/10653144/168504659-a4297558-219a-438e-bdb6-f75bc04a9691.png">

**Comment by mittwillson** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/10653144/168505303-ec4a26c7-475f-46df-b867-1bf09cfa8db7.png">

这里是不是应该禁止输入其他字符，感觉会很奇怪

**Comment by JayJay1024** [comment]
> <img alt="image" width="513" src="https://user-images.githubusercontent.com/10653144/168505303-ec4a26c7-475f-46df-b867-1bf09cfa8db7.png">
> 
> 这里是不是应该禁止输入其他字符，感觉会很奇怪

这里应该不用禁止了，这里用了antd的InputNumber组件，只关心number输入，而且上面有提示输入0-100

**Comment by mittwillson** [comment]
> > <img alt="image" width="513" src="https://user-images.githubusercontent.com/10653144/168505303-ec4a26c7-475f-46df-b867-1bf09cfa8db7.png">
> > 这里是不是应该禁止输入其他字符，感觉会很奇怪
> 
> 这里应该不用禁止了，这里用了antd的InputNumber组件，只关心number输入，而且上面有提示输入0-100

但依旧还是能输入其他非 number 字符串，并且输入 `1%` 的时候它的校验也通过了

**Comment by JayJay1024** [comment]
> > > <img alt="image" width="513" src="https://user-images.githubusercontent.com/10653144/168505303-ec4a26c7-475f-46df-b867-1bf09cfa8db7.png">
> > > 这里是不是应该禁止输入其他字符，感觉会很奇怪
> > 
> > 
> > 这里应该不用禁止了，这里用了antd的InputNumber组件，只关心number输入，而且上面有提示输入0-100
> 
> 但依旧还是能输入其他非 number 字符串，并且输入 `1%` 的时候它的校验也通过了

可以输入但是不响应那个%号。我在onChange中试过不响应非number，所以如果确实想不让输入非number就不能用InputNumber了，我感觉暂时先这样吧
