### ISSUE TITLE
账户切换数据重载的面板应该显示 loading

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#158]
比如 https://apps.darwinia.network/staking?active=power staking页面包含四个面板需要刷新数据，如果切换账户后数据是没有立即刷新的，应该新增 loading 状态来确保用户会等待新的数据拉取完成，而不是误认为页面的数据是当前账户的

**Comment by ZolaxZola** [comment]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/102211220/173502586-e5241321-d5b7-49ee-841a-99857c6c5ca3.png">
after withdrawing successfully， the unbonded data will not be refreshed immediately

**Comment by JayJay1024** [comment]
> <img alt="image" width="1213" src="https://user-images.githubusercontent.com/102211220/173502586-e5241321-d5b7-49ee-841a-99857c6c5ca3.png">
> 
> after withdrawing successfully， the unbonded data will not be refreshed immediately

this has been fixed in [5f32645](https://github.com/darwinia-network/apps/pull/213/commits/5f3264581cc9a1f06748115bbcccfd0fc7a20b4e)

**Comment by JayJay1024** [comment]
这个issue标题有点宽泛。现在获取数据基本加了loading，这个issue就先关闭了，有问题可以重新开一个issue
