### ISSUE TITLE
Opening graph links not working

### ISSUE THREAD

**Issue by SasoLithops** [darwinia-network/apps#183]
Hello team!

At https://apps.darwinia.network/staking?active=targets, when clicking graph icon at the right end link changes and doesn't open what is supposed too? It is supposed to stopped working correctly three weeks ago.

Can you please have a look?

Thank you

**Comment by SasoLithops** [comment]
![IMG_20220531_214645_255.jpg](https://user-images.githubusercontent.com/101176902/171272321-1488ba7c-8b59-4a1f-805c-43022d3dd25e.jpg)

**Comment by ZolaxZola** [comment]
Thank you for your feedback.😊 
Sorry for the inconvenience. We plan to remove the redirect link and later support the display of validator-related data charts within the Darwinia apps. Stay tuned!
