### ISSUE TITLE
Amount problem

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/apps#185]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/80877629/171341263-56bdb15e-8fb0-43f5-ad1d-f56c91937972.png">
2qdnTkrbHocmJqhKWap3Na44uhrEzjQsHhU7AVMUH2zzic2N

**Comment by JayJay1024** [comment]
this account is not a stash account and, there is no staking lock with this account. maybe he lock for another reason but no staking

https://darwinia.subscan.io/account/2qdnTkrbHocmJqhKWap3Na44uhrEzjQsHhU7AVMUH2zzic2N

<img width="921" alt="image" src="https://user-images.githubusercontent.com/21007682/171393440-373cfe63-1a44-443c-ae49-293ce38e2c4f.png">

**Comment by JayJay1024** [comment]
staking lock is like this:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/21007682/171394448-aa003535-bbf5-489f-bba4-fadbe6554467.png">

**Comment by JayJay1024** [comment]
As described above, close this issue now, if there is a problem, can reopen it
