### ISSUE TITLE
旧版本的apps 中 “Lock extra” 功能支持将已经Bond的token 转换成 lock 的状态，新版本这个功能缺失

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/apps#21]
<img width="298" alt="image" src="https://user-images.githubusercontent.com/80877629/155884151-0bd10cb4-3ea0-4a9f-896f-feb577ece30e.png">

**Comment by sxlwar** [comment]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/20088392/157157366-0bc5bbbc-de60-4073-9ac7-5ff1cd4f90f5.png">
?

**Comment by 1022ranji** [comment]
是指之前这个lock extra 的功能在用户填写amount 的时候可以把bonded中的balance也一起加进去，直接把bonded的钱变成locked. 但是现在新的apps中这个功能只能够允许用户填写可用的那部分balance, 不允许用户直接把bonded的那部分数量直接转成locked. 
cc @WoeOm

**Comment by sxlwar** [comment]
改过了
