### ISSUE TITLE
在使用Apps的时候, api 经常会断开，需要优化一下

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/apps#22]
在使用Apps的时候，经常会出现下面图中的情况：
![image](https://user-images.githubusercontent.com/80877629/155953816-9e171a6f-cee8-4483-8a8c-556f0976c61f.png)
<img width="655" alt="image" src="https://user-images.githubusercontent.com/80877629/155953672-4f4406fa-e7e8-43de-b365-9c473e7f7dea.png">

**Comment by sxlwar** [comment]
is crab？

**Comment by 1022ranji** [comment]
Both Darwinia and Crab.
