### ISSUE TITLE
Should we let users to rebond the unbonded asset?

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/apps#224]
![image](https://user-images.githubusercontent.com/102211220/174009419-d2eb1557-96f8-41b6-a68e-3056a6697e49.png)
Not Sure about the design now after runtime upgrading

My opinion is no. The unbonded asset means it's ready for withdrawing to the available balance. Users can rebond only the unbonding assets which is still in the 14-day unbonding period. 
Need some more discussion about this.

**Comment by JayJay1024** [comment]
Logically speaking, `unbonded` can also be `rebond`. We can find a chance to test it.
It seems that `unbonded` is classified by ourselves?

**Comment by JayJay1024** [comment]
Are there any plans for this issue now?

**Comment by ZolaxZola** [comment]
Will take this into consideration when designing the account page
