### ISSUE TITLE
质押金额输入触发格式化会导致输入异常

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#236]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/10653144/174585662-47f1cf8a-da40-4523-943e-d58b1c94eab8.png">

在输入一个2以后，输入框会被格式化为 `2.000000000` 并将指针移到最后，导致我想连续输入 `200`，但会变成 `2.00000000000`

并且该输入框不支持键盘左右移动位置

**Comment by ZolaxZola** [comment]
![image](https://user-images.githubusercontent.com/102211220/174725690-7acada4c-f544-4b81-a97b-36e3d5a55eba.png)
happens in the input box in `bond more`，`unbond funds`，`lock extra`， `rebond funds `Pop-up window
