### ISSUE TITLE
A tool to decode call bytes of specific chain

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/apps#244]
Input: a encoded dispatch call data
output: the call's decoded representation

**Comment by hackfisher** [comment]
Better to support this in 2 weeks before upgrade of v0.12.3

**Comment by hackfisher** [comment]
> output: the call's decoded representation

Human readable, just like some proposal preimage rendering on https://polkadot.js.org/apps . Or some call rendering on subscan. (polkadot.js.org is better and easy for apps to adopt)

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.public.curie.radiumblock.co%2Fws#/democracy

![image](https://user-images.githubusercontent.com/1070122/175471315-4ba2a46b-ac65-40b9-b60b-5e30d44e2923.png)


<img width="1258" alt="image" src="https://user-images.githubusercontent.com/1070122/175471506-51fbac28-8df9-4988-8d33-7ceb98b6d785.png">

**Comment by JayJay1024** [comment]
refer: #246

**Comment by aurexav** [comment]
https://polkadot.js.org/apps/?rpc=wss://pangolin-rpc.darwinia.network#/extrinsics/decode
