### ISSUE TITLE
存单状态显示

### ISSUE THREAD

**Issue by AlexChien** [darwinia-network/apps#254]
存单状态的用词有问题

1. 已过期：已经到期的存单的状态应称为为“已到期”，而不是“已过期”
2. 已领取：到期的存单如果被领取后，应显示为“已领取”

**Comment by JayJay1024** [comment]
这里最新代码进行了重构，生产环境暂时还需要等发布版本才能看到

**Comment by JayJay1024** [comment]
新版版「状态」改为了「Action」，这个issue先关闭了
