### ISSUE TITLE
存单释放失败

### ISSUE THREAD

**Issue by AlexChien** [darwinia-network/apps#255]
在配置了controller账号的stash地址进行存单释放操作时，当前版本APP在签名时默认只能用stash地址进行，导致领取失败，应该允许使用controller账号进行签名，则可纠正该错误。

**Comment by JayJay1024** [comment]
这个问题修复了，不过还没有发版本

**Comment by ZolaxZola** [comment]
现在发版到生产环境了

**Comment by ZolaxZola** [comment]
been resolved
