### ISSUE TITLE
质押页面白屏

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#26]
复现环境：Mac m1 chrome 98.0.4758.109
Polkadot插件：0.42.2
描述：
> 在polkadot插件内无账户的情况下，访问 https://apps.darwinia.network/ 页面，没有连接钱包的情况下，切换 `质押` 页面会白屏且无任何提示和动画

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/10653144/156687723-c65dadc8-8438-453d-8dc4-9b75c924b512.png">

**Comment by 1022ranji** [comment]
fixed
