### ISSUE TITLE
CKTON Balance Display Error？

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/apps#264]
![image](https://user-images.githubusercontent.com/102211220/177260765-f38d2442-2e0c-4575-ad13-a33eac325e09.png)
![image](https://user-images.githubusercontent.com/102211220/177260922-23a69bba-fa01-4296-bb30-44ca526e3661.png)
![image](https://user-images.githubusercontent.com/102211220/177260802-0f6adeaf-4413-4287-bc3f-1a14e648a5e7.png)

**Comment by JayJay1024** [comment]
The decimals display here is 3, so it shows 0 for this case

**Comment by JayJay1024** [comment]
Do we need to increase the precision? If not, can this issue be closed?

**Comment by ZolaxZola** [comment]
One suggested solution here is to keep the current precision and make a small addition. Besides that, the Hover window shows the full 9 decimal places when the mouse hovered. (not only the KTON but also the RING) 
The effect is a bit like this
![image](https://user-images.githubusercontent.com/102211220/178882990-b87ef455-2699-4e9f-98df-4e227806ba5f.png)
