### ISSUE TITLE
Unlock Earlier时，Stash账户的KTON初始余额-罚款KTON数额≠ 支付罚款后KTON余额

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/apps#268]
测试环境：https://apps-9cr5w3hqh-itering.vercel.app/account

以Pangolin网络为例
Stash: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
Controller: the same as the Stash account

Stash账户的KTON初始余额 300.017036594 PKTON  ｜ UI显示罚款数额：0.011891619 PKTON ｜ 支付罚款后余额 300.017036594
![image](https://user-images.githubusercontent.com/102211220/177507460-47b010b2-4eb9-44f6-a631-28066e2c97ba.png)

**期望成立的等式：**
Stash账户初始PKTON余额- 罚款数额=支付罚款后KTON余额

**实际：**
300.017036594-0.011891619=**300.005144975**  （**≠ 300.017036594** ）

**Comment by JayJay1024** [comment]
https://github.com/darwinia-network/darwinia-common/blob/main/frame/staking/src/lib.rs#L1548-L1553

X: compute_kton_reward 就是计算奖励的公式
X: 假设锁三个月，只过了一个月就解锁
X: (三个月奖励 - 一个月奖励) * 3 = 罚金
J: 这里一个月，就是按30天时间戳是吗
X: https://github.com/darwinia-network/darwinia-common/blob/main/frame/staking/src/primitives.rs#L47
