### ISSUE TITLE
Over 16 validators nominated 

### ISSUE THREAD

**Issue by SasoLithops** [darwinia-network/apps#274]
Hi team!

Our member found that if he nominates more then 16 validators the UI doesn't stop him.

He gets this error message “too many targets” 

That is how we recognized the error.

He claims:

Why does the UI let me select too many targets? It should stop at max
In polkadot.js app normally limits the target count.

If it is not too much work now,maybe our App could do the same. I also always count not to nominate too much😊

Thank you and congrats again for the parachain yesterday 🍾🎉

**Comment by AurevoirXavier** [comment]
> Hi team!
> 
> Our member found that if he nominates more then 16 validators the UI doesn't stop him.
> 
> He gets this error message “too many targets”
> 
> That is how we recognized the error.
> 
> He claims:
> 
> Why does the UI let me select too many targets? It should stop at max In polkadot.js app normally limits the target count.
> 
> If it is not too much work now,maybe our App could do the same. I also always count not to nominate too much😊
> 
> Thank you and congrats again for the parachain yesterday 🍾🎉

I can't find the too many targets. What's the origin error msg?

**Comment by JayJay1024** [comment]
> Hi team!
> 
> Our member found that if he nominates more then 16 validators the UI doesn't stop him.
> 
> He gets this error message “too many targets”
> 
> That is how we recognized the error.
> 
> He claims:
> 
> Why does the UI let me select too many targets? It should stop at max In polkadot.js app normally limits the target count.
> 
> If it is not too much work now,maybe our App could do the same. I also always count not to nominate too much😊
> 
> Thank you and congrats again for the parachain yesterday 🍾🎉

Thanks🍻
We will check and fix this today

**Comment by aurexav** [comment]
- 24 for Crab
  https://github.com/darwinia-network/darwinia/blob/main/runtime/crab/src/pallets/staking.rs#L52
- 16 for Darwinia
  https://github.com/darwinia-network/darwinia/blob/main/runtime/darwinia/src/pallets/staking.rs#L52

**Comment by SasoLithops** [comment]
Thank you💪
