### ISSUE TITLE
质押页面提名人列表错误

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#28]
- 提名人列表里有非常非常多的账户地址并且power都是0且不是我的提名人，这个好像目前我的账户是必定复现
- 名字位置预留的空间过短，建议优化

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/10653144/156736947-688790e5-3bcc-413c-ac7b-117f2d4d7797.png">

**Comment by JayJay1024** [comment]
这个问题还在吗？可以贴下你的账号吗

**Comment by mittwillson** [comment]
> 这个问题还在吗？可以贴下你的账号吗

还存在的，`2qi3VKjQ7aV2Yy5em2DtyR9hyNuFHghryND27dDJvMzcdUUN`
