### ISSUE TITLE
`0` or `0 PRING`

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/apps#315]
![image](https://user-images.githubusercontent.com/11801722/180964495-66c45c9c-d540-4375-802d-9ca9c5def500.png)

I'm not sure if this is intentional, but I think it would be nice to have a consistent display format.

**Comment by JayJay1024** [comment]
Yeah it is intentional. I thought 0 would be more conspicuous. Would it be better to show `0 PRING` ?

**Comment by boundless-forest** [comment]
It's okay to me. Just to confirm the design.
