### ISSUE TITLE
Display the initial quote 

### ISSUE THREAD

**Issue by boundless-forest** [darwinia-network/apps#316]
![image](https://user-images.githubusercontent.com/11801722/180970302-1d0d8b20-5f06-458e-9f8c-11fa2ed3e845.png)

For relayers newly registered in the fee market, the initial quote should be displayed.

**Comment by JayJay1024** [comment]
Fixed code: https://github.com/darwinia-network/apps-subql/pull/4
I want to fix this issue after migrate to darwinia-network/indexer because syncing blocks is too slow now
