### ISSUE TITLE
Add a warning about not transferring RING/ CRAB/KTON/CKTON to Ledger Account 

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/apps#317]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/102211220/181270758-2dcffb36-6f91-4328-bf41-eec97402c8cf.png">

**Comment by JayJay1024** [comment]
Can you post the translation? How about "不要转到Ledger钱包或者交易所控制的账号中" @ZolaxZola

**Comment by ZolaxZola** [comment]
> Can you post the translation? How about "不要转到Ledger钱包或者交易所控制的账号中" @ZolaxZola

Hi, I've updated in Figma. Please check the content.

**Comment by JayJay1024** [comment]
> > Can you post the translation? How about "不要转到Ledger钱包或者交易所控制的账号中" @ZolaxZola
> 
> Hi, I've updated in Figma. Please check the content.

Got it

**Comment by ZolaxZola** [comment]
Hi, the warning has to be added also when transferring KTON/CKTON.
