### ISSUE TITLE
Suggest to Remove the Serial numbers on Staking-Target Page

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/apps#344]
the number here seems meaningless, especially after marking the favorite validators. Get even confused.
We can remove them.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/102211220/190617907-4c4738a3-5fa7-45e1-91e8-4edf31e7a14c.png">

**Comment by JayJay1024** [comment]
I saw polkadot apps like this, so didn't remove it

**Comment by ZolaxZola** [comment]
> I saw polkadot apps like this, so didn't remove it

OK, Forget my words. The number here is sorted by active commission. Let's keep it.
