### ISSUE TITLE
表单左右滑动滚动问题

### ISSUE THREAD

**Issue by JayJay1024** [darwinia-network/apps#35]
未复现

**Comment by DreUncle** [comment]
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/34929683/157366445-ac8a0cee-1b0a-4735-8ac1-40361db216e6.png">
在不该出现滚动条的地方经常出现空白滚动条，有时候右边也有

**Comment by DreUncle** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/34929683/157366511-221e462a-d5e0-43ad-964c-da972f49ad16.png">

**Comment by DreUncle** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/34929683/157366594-2b651e16-1a6e-4c13-b1e5-6ad77a39d41f.png">

**Comment by DreUncle** [comment]
<img width="1784" alt="image" src="https://user-images.githubusercontent.com/34929683/157367678-28664bc1-83c1-487c-b3dd-a8b9dcfc077a.png">

**Comment by JayJay1024** [comment]
这是滚动条吗还是框
@sxlwar 你有出现吗
我在开发和正式环境都看不到
