### ISSUE TITLE
Minor update of button English texts

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/apps#360]
![image](https://user-images.githubusercontent.com/102211220/201563819-0b0404e5-36a2-4ee2-b471-b1c23235a9da.png)
Button text: Validator > Validate
<img width="714" alt="image" src="https://user-images.githubusercontent.com/102211220/201565136-24a9b872-8a02-4553-a615-280104cae613.png">
Button text: Staking > Stake

**Comment by isunaslabs** [comment]
Got it!
