### ISSUE TITLE
Add 2.0 multisig dapp

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/apps#366]
https://ipfs.io/ipfs/QmfRD4GuqZobNi2NT2C77a3UTQ452ffwstr4fjEJixUgjf/#/wallets

**Comment by isunaslabs** [comment]
@wuminzhe I need the name and the description of this link 
![image](https://user-images.githubusercontent.com/15822234/231414234-c8638aef-b6ec-4aae-8db0-283b118bacb1.png)
