### ISSUE TITLE
Link to app without network identity

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/apps#368]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/1608576/231681288-202920cc-8867-4fd7-8ef3-da5710dd009c.png">

do we need to make our dapps work with the selected network? @1022ranji

**Comment by 1022ranji** [comment]
Yes, Darwinia Staking is currently bound to this Dapp. After Darwinia2 is upgraded, the staking Dapp(staking.darwinia.network) will support Darwinia2. At that time, this page will remove the network restriction

**Comment by 1022ranji** [comment]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/80877629/233895070-7f9469ad-5f28-4084-b1d0-ff7a6b603d1a.png">

**Comment by 1022ranji** [comment]
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/80877629/233895289-313a1a7a-8870-406d-ae3f-7cf3de103492.png">

**Comment by 1022ranji** [comment]
<img width="168" alt="image" src="https://user-images.githubusercontent.com/80877629/233895417-bcd649db-d266-48c8-9507-2d054ca62514.png">
Discord link: https://discord.com/invite/VcYFYETrw5

**Comment by 1022ranji** [comment]
done
