### ISSUE TITLE
API超时重连会重置页面

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#38]
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/10653144/157358681-859de298-2d8f-4702-9d85-9961c275a05f.png">

访问 https://apps.darwinia.network/portal 页面停留大概1分多钟后，会显示API连接并且页面白屏，恢复的时候会重置页面的状态，丢失用户态数据

**Comment by 1022ranji** [comment]
done
