### ISSUE TITLE
Migrate to Next.js to support better SEO

### ISSUE THREAD

**Issue by JayJay1024** [darwinia-network/apps#380]

**Comment by wuminzhe** [comment]
through server side rendering?

**Comment by JayJay1024** [comment]
> through server side rendering?

yeah, one of them

**Comment by wuminzhe** [comment]
> > through server side rendering?
> 
> yeah, one of them

What's the underling method of react ssr? Can you make a share of it after you are ready?

**Comment by JayJay1024** [comment]
> > > through server side rendering?
> > 
> > 
> > yeah, one of them
> 
> What's the underling method of react ssr? Can you make a share of it after you are ready?

Yeah should be ok next week

**Comment by nblogist** [comment]
can this be closed now?

**Comment by JayJay1024** [comment]
> can this be closed now?

Yeah, I close it for now.
