### ISSUE TITLE
Envio is not visible in the apps.darwinia.network - upon investigation we found out that the checks aren't completely passed and there is a vercel deployment issue: https://github.com/darwinia-network/apps/pull/413/checks can you please have a look at it? - in local deployments Envio shows up fine

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/apps#414]
@hackfisher as pointed out by @Jordy-Baby that Envio is not visible in the apps.darwinia.network - upon investigation we found out that the checks aren't completely passed and there is a vercel deployment issue: https://github.com/darwinia-network/apps/pull/413/checks can you please have a look at it? - in local deployments Envio shows up fine
![image](https://github.com/darwinia-network/apps/assets/35498810/4b66f174-e69f-415b-892a-83791f3fc879)

_Originally posted by @nblogist in https://github.com/darwinia-network/apps/pull/413#issuecomment-2196624952_

**Comment by fewensa** [comment]
Release new tag will be deploy to apps.darwinia.network I'm already create it.

**Comment by nblogist** [comment]
Thank you @fewensa
