### ISSUE TITLE
验证人页面搜索输入卡顿明显

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#43]
https://apps.darwinia.network/staking?active=overview

页面搜索功能在按下字符时会卡一下，连续输入时能明显感觉卡顿，需要优化

或许可以改进下异步方法或延迟响应来减免连续输入时的卡顿

<img width="604" alt="image" src="https://user-images.githubusercontent.com/10653144/157417868-b59b5060-2460-44ed-bb1d-1f90f3169a1e.png">

**Comment by 1022ranji** [comment]
fixed
