### ISSUE TITLE
提名验证人搜索框关键字索引有问题

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#45]
![telegram-cloud-photo-size-5-6149925893066305321-y](https://user-images.githubusercontent.com/10653144/157819953-70322c4b-eb36-4883-b1d8-dcd6ddbe9ea0.jpg)

![telegram-cloud-photo-size-5-6149925893066305322-y](https://user-images.githubusercontent.com/10653144/157819961-28392067-4b97-4262-8488-7485a9132495.jpg)

**Comment by 1022ranji** [comment]
通过这个页面的提名可以复现这个问题 cc @JayJay1024 
<img width="1579" alt="image" src="https://user-images.githubusercontent.com/80877629/158521366-e45ff2b2-4fbb-4d77-80bd-7dedc0c269d4.png">
