### ISSUE TITLE
质押锁定Power缺少锁定期限因素 

### ISSUE THREAD

**Issue by mittwillson** [darwinia-network/apps#46]
锁定期限无论选多久，Power都没有变化

<img width="553" alt="image" src="https://user-images.githubusercontent.com/10653144/157821199-d1d19bb2-6a8b-49d2-9f0f-4986e60d0e77.png">

<img width="529" alt="image" src="https://user-images.githubusercontent.com/10653144/157821261-767b6f3e-b007-4a2b-bd96-aa9b3396f016.png">

**Comment by 1022ranji** [comment]
Power只与质押的数量有关，与锁定时长无关
