### ISSUE TITLE
 Handle  API disconnect

### ISSUE THREAD

**Issue by sxlwar** [darwinia-network/apps#5]
better UX

**Comment by 1022ranji** [comment]
<img width="1751" alt="image" src="https://user-images.githubusercontent.com/80877629/157365916-c03795bf-e382-4c79-aef5-9c3ef4b7b23c.png">
当前disconnect时，直接是白屏的状态，需要把白屏去掉

**Comment by JayJay1024** [comment]
this should have been fixed

**Comment by 1022ranji** [comment]
This issue has been fixed.
