### ISSUE TITLE
bug: 部分用户获得power后无法提名，同时新版本与旧版本的power数量不一致，具体见下图

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/apps#50]
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/80877629/158146934-684993af-80b0-4b57-aacd-91bae43f23dc.png">
在旧版本中，可以提名，如下图：
<img width="1573" alt="image" src="https://user-images.githubusercontent.com/80877629/158147069-53c1344f-2365-41ca-ba9e-2dc11de1a564.png">

**Comment by 1022ranji** [comment]
该账户地址：2oXKyw2JuXf74toFspg8rFHuyWb8NedDJUXP9mDLqzNXeSA7

**Comment by sxlwar** [comment]
https://github.com/darwinia-network/legacy-apps/issues/307
power应该和修复这个 issue 的有关系

**Comment by sxlwar** [comment]
https://github.com/darwinia-network/apps/blob/31ba133f9a6c40cef1cf7f86ec09d40fee19d151/src/components/staking/power/Power.tsx#L30
@JayJay1024 
button 被禁用需要看下原来的逻辑

**Comment by 1022ranji** [comment]
新的账户点击“Staking now”的时候，弹出的提示框显示交易成功，但是查看交易详情的时候显示失败。https://darwinia.subscan.io/account/2tKQCR12ZrTNggb4iPUe2j8QsjLi4CRkdB6WL8dUAFMwdfJD
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/80877629/158293545-b991e047-350c-49e3-90ca-a41495b1206e.png">
上图中，在账户余额为100的情况下，stake 10, 在新版的apps中显示失败，在最上方老apps中显示成功。看起来是这个value的值有关 cc @JayJay1024 @sxlwar 
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/80877629/158293689-ab707d01-15b9-4021-90ad-1efdc278d686.png">

**Comment by JayJay1024** [comment]
> 该账户地址：2oXKyw2JuXf74toFspg8rFHuyWb8NedDJUXP9mDLqzNXeSA7

该账号设置了另一个staking controller地址`2pVRrhjrwGF5iQXySxjPWpuCNYQ9MhzstsPN2CzGxYzdCvrk`，所以不让该账号提名了。这个限制是合理的吗？

**Comment by JayJay1024** [comment]
> 新的账户点击“Staking now”的时候，弹出的提示框显示交易成功，但是查看交易详情的时候显示失败。https://darwinia.subscan.io/account/2tKQCR12ZrTNggb4iPUe2j8QsjLi4CRkdB6WL8dUAFMwdfJD <img alt="image" width="1269" src="https://user-images.githubusercontent.com/80877629/158293545-b991e047-350c-49e3-90ca-a41495b1206e.png"> 上图中，在账户余额为100的情况下，stake 10, 在新版的apps中显示失败，在最上方老apps中显示成功。看起来是这个value的值有关 cc @JayJay1024 @sxlwar <img alt="image" width="1321" src="https://user-images.githubusercontent.com/80877629/158293689-ab707d01-15b9-4021-90ad-1efdc278d686.png">

#57

**Comment by 1022ranji** [comment]
fixed
