### ISSUE TITLE
Staking reward account

### ISSUE THREAD

**Issue by SasoLithops** [darwinia-network/apps#77]
Hi!

This person could not see rewards in his account.

https://darwinia.subscan.io/nominator/2orPXVTGD1meA3G4yvMteqZKR7ttJbP9edNJ2GNuDY4y9W4f?tab=reward

Can someone please explain to me why his receiving rewards are on different account then shown above as his rewards account?
Did he do something wrong?Or am I am reading into this wrong.
Thank you.
Saso

**Comment by 1022ranji** [comment]
Hi!
Staking rewards can be assigned to any account. There are two different rewards accounts through this link that you gave before. This parameter can be set by using the "change reward destination" function.
<img width="593" alt="image" src="https://user-images.githubusercontent.com/80877629/160324170-bde202d1-f03b-45a3-9de5-0adb8d1fa6ab.png">
And through this link: https://darwinia.subscan.io/account/2orPXVTGD1meA3G4yvMteqZKR7ttJbP9edNJ2GNuDY4y9W4f 
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/80877629/160324593-50cc046f-b4c5-4db0-8bb4-c5aa7929e7a6.png">
You can see the account change the reward destination 7 days ago.

**Comment by SasoLithops** [comment]
Hi!

Thank you for explaining.It seems so basic when you do. I spent three hours on this🙃

**Comment by 1022ranji** [comment]
Thank you! This is a great question for us to know the users' confusion.

**Comment by SasoLithops** [comment]
Thanks Ran Ji☺️ I have another that gets them confused will post.I never
quite know if I can post as it might be really basic for you guys.I don't
want to bother you ad I know you work a lot.

V pon., 28. mar. 2022 08:59 je oseba RANJI ***@***.***>
napisala:

**Comment by 1022ranji** [comment]
Creating an issue is the best approach to reflect the bug (or your confusion), and is the best way for us to address the issue as well. (The confusing parts might be where we can optimize.)

**Comment by SasoLithops** [comment]
Noted👍
