### ISSUE TITLE
unable to find injected

### ISSUE THREAD

**Issue by SasoLithops** [darwinia-network/apps#83]
Hi!

Three people so far asked about this issue:

When trying to bond an error shows "unable to find injected".

![IMG_20220328_100053_283.png](https://user-images.githubusercontent.com/101176902/160353273-f2d5ef5f-ab59-40f3-98e5-941224e2a294.png)

We found a way to help them by restoring or reinstalling polkadot.js wallet and it worked.
So actually "not" an issue, this is just to let you know.

Thank you!

**Comment by 1022ranji** [comment]
This displays that the account can not be found in the polkadot.js extension, so cannot sign for this extrinsic.
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/80877629/160379334-b5b59a24-dec5-4906-b48f-e2ecce68bfa7.png">

**Comment by SasoLithops** [comment]
Sorry I still don't understand☺️ As it shows the same for me and works fine...

![IMG_20220328_123601.jpg](https://user-images.githubusercontent.com/101176902/160380752-ff9e1f11-19d6-4fd6-a0a3-8eefc96a114f.jpg)

**Comment by 1022ranji** [comment]
Normally it shows like this：
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/80877629/160382443-f18dc466-f03f-49c1-9989-cbf6da74335e.png">
But in this situation, if there is a tip like the picture shown below, it means the account can not be found in the polkadot.js extension, the solution is to import this account to polkadot.js extension:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/80877629/160382659-a0b07555-e2bc-4815-9ade-46b54b35bc0c.png">

**Comment by SasoLithops** [comment]
Understand now.Thank you for taking time,to explain it to a dev noobie like me☺️
