### ISSUE TITLE
未对账户“可用网络”做出限制，建议增加限制

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/apps#87]
创建账户时选择了“仅kusama网络可用”，但在apps里，crab网络下，账户依然可见可用。
建议按用户实际设置，作出相应限制。
<img width="824" alt="image" src="https://user-images.githubusercontent.com/102211220/160973249-f177cc03-7402-4a9b-9e21-c7cf47ca14e4.png">

**Comment by JayJay1024** [comment]
这个应该只是这里的「display address format」
<img width="332" alt="image" src="https://user-images.githubusercontent.com/21007682/162360888-a6decbc1-629a-4fea-997d-3adc45eec2b6.png">

在这里设置不可见就会不可用
<img width="165" alt="image" src="https://user-images.githubusercontent.com/21007682/162361018-f9553c84-81c9-4402-acf7-71ad8c8cdf21.png">

**Comment by JayJay1024** [comment]
这个暂时无法识别设置的仅哪个网络可用
