### ISSUE TITLE
发送交易报错 

### ISSUE THREAD

**Issue by freehere107** [darwinia-network/apps#88]
<img width="703" alt="image (2)" src="https://user-images.githubusercontent.com/7080674/161216036-1f19a782-ea45-4f4f-8a45-94a64a4eb33d.png">
<img width="823" alt="image (1)" src="https://user-images.githubusercontent.com/7080674/161216045-70ee6cf1-1e1b-4eb6-9454-db984ca2c2ba.png">

**Comment by freehere107** [comment]
claim reward 应该不需要controller 签名，更改controller后页面未更新controller 信息

**Comment by 1022ranji** [comment]
claim reward 确实不需要 controller 签名  @JayJay1024

**Comment by JayJay1024** [comment]
> 更改controller后页面未更新controller 信息

是不是设置controller没有成功。同个地址不能同时被多个账号设置为controller

**Comment by freehere107** [comment]
不是，第一次成功后没更新我才发了第二笔交易，第二笔交易失败了

**Comment by JayJay1024** [comment]
> 不是，第一次成功后没更新我才发了第二笔交易，第二笔交易失败了

第一笔「Set Controller」成功了，但是页面没更新，所以又发了一笔「Set Controller」，然后选的是和第一笔一样的Account？

**Comment by freehere107** [comment]
是的，https://crab.subscan.io/account/5HZCxSCVC9kMbxzBbf2L9rRwJRrXmjtcHsw8EyFkitxriTnk

**Comment by JayJay1024** [comment]
那是会失败的。这个后面会提示被设置为Controller了就不能再被设置了 (#94 )
