### ISSUE TITLE
交易发送框label

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/apps#90]
这两个label感觉不是很好，一个是account一个是Address，而且最前面都是Send，还不如一个Sender一个Receiver

![image](https://user-images.githubusercontent.com/15799431/161239537-2b9b19e4-4de3-4bff-89ea-537f5ff0108f.png)

**Comment by JayJay1024** [comment]
https://polkadot.js.org/apps/ 也是这样提示的。需要修改一下吗 @1022ranji @ZolaxZola 不过第二个「Address」应该首字母小写比较统一
<img width="566" alt="image" src="https://user-images.githubusercontent.com/21007682/162360045-f966854c-ff8b-4de6-b29b-7528a4c693e7.png">

**Comment by ZolaxZola** [comment]
看了一下波卡这边，我猜测，send from 用了account，而 send to 用了address，
想要表达出，「发送账户」从 **可选accounts**中选择，而「接收账户」除了从 **可选accounts**中选择，还能粘贴一个**address**过来 这层意思。（hh
我觉得可以统一下大小写即可
@1022ranji  @xiaoch05

**Comment by 1022ranji** [comment]
可能不需要太麻烦，写 sender 和 receiver 直接区分就可以

**Comment by xiaoch05** [comment]
嗯，直接Sender和Receiver，之前那种方式两个都是 send 开头一眼看上去不容易区分

**Comment by JayJay1024** [comment]
[b150890](https://github.com/darwinia-network/apps/pull/103/commits/b15089028c1d301806ec9c4ce547838395d51cd1)
