### ISSUE TITLE
Preview the staking information(stash account/controller) of your accounts at a glance

### ISSUE THREAD

**Issue by JayJay1024** [darwinia-network/apps#95]
比如stash的controller
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/21007682/161361671-b1079b44-df83-4e85-a9c2-6f648bd93d7b.png">

**Comment by ZolaxZola** [comment]
![image](https://user-images.githubusercontent.com/102211220/171122329-7812c63c-c068-40ad-9fc8-06c4c7843229.png)
Take this design into consideration.
In this pic, Stash Account on the left is the currently connected account.(click here to change the connected account) 
 On the right, the controller is displayed. (click here to change the controller)
Just mark here for reference only 💡
